# Generated by Django 5.0.3 on 2024-03-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0004_alter_education_graduation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificates',
            name='photo_name',
            field=models.CharField(default='certi.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='certificates',
            name='skills',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
