# Generated by Django 5.0.3 on 2024-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0005_certificates_display_order_certificates_photo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='certificates/')),
                ('issued_by', models.CharField(max_length=100)),
                ('date_awarded', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('skills_gained', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
