# Generated by Django 5.0.3 on 2024-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0006_certificate_delete_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='viralapp/static/images/certificates/'),
        ),
    ]
