# Generated by Django 5.0.3 on 2024-03-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0011_alter_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
