# Generated by Django 5.0.3 on 2024-03-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0013_remove_projects_user_projects_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='code_type',
            field=models.TextField(blank=True),
        ),
    ]
