# Generated by Django 5.0.3 on 2024-03-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0014_projects_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='live_link',
        ),
        migrations.AddField(
            model_name='projects',
            name='project',
            field=models.URLField(blank=True),
        ),
    ]
