# Generated by Django 5.0.3 on 2024-04-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0017_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='display_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
