# Generated by Django 5.0.3 on 2024-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0020_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(upload_to='certificate/'),
        ),
    ]
