# Generated by Django 5.0.3 on 2024-04-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viralapp', '0021_alter_certificate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(upload_to='files/resume/'),
        ),
    ]
